Traceback (most recent call last):
  File "/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importa bibliotecas; inicializa vari√°veis; define fun√ß√µes.
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from datetime import datetime
import auto_ts as AT
import math as mt
from sklearn.metrics import mean_squared_error
import seaborn as sns

colunas = ['data','total','ibc','pib','consumo', 'ICST-R', 'geracaoGWh','IndGeral']

mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False

dados_autoML = pd.read_csv('dadosRonaldo.csv')
dados_autoML.head()

df = dados_autoML[colunas]
df = df.set_index('data')
df.index = pd.to_datetime(df.index)

df.info()

print ("Rows     : " ,df.shape[0])
print ("Columns  : " ,df.shape[1])
print ("\nFeatures : \n" ,df.columns.tolist())
print ("\nMissing values :  ", df.isnull().any())
print ("\nUnique values :  \n",df.nunique())

df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-0e5f51a1ee2f>[0m in [0;36m<module>[0;34m[0m
[1;32m      4[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mfrom[0m [0mdatetime[0m [0;32mimport[0m [0mdatetime[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0;32mimport[0m [0mauto_ts[0m [0;32mas[0m [0mAT[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0;32mimport[0m [0mmath[0m [0;32mas[0m [0mmt[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mmetrics[0m [0;32mimport[0m [0mmean_squared_error[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/adp255/env_adp255/lib/python3.9/site-packages/auto_ts/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     39[0m [0;31m#######################################[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     40[0m [0;31m# Models[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 41[0;31m [0;32mfrom[0m [0;34m.[0m[0mmodels[0m [0;32mimport[0m [0mBuildBase[0m[0;34m,[0m [0mBuildArima[0m[0;34m,[0m [0mBuildAutoSarimax[0m[0;34m,[0m [0mBuildVAR[0m[0;34m,[0m [0mBuildML[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     42[0m [0;32mfrom[0m [0;34m.[0m[0mmodels[0m[0;34m.[0m[0mbuild_prophet[0m [0;32mimport[0m [0mBuildProphet[0m[0;34m[0m[0;34m[0m[0m
[1;32m     43[0m [0;34m[0m[0m

[0;32m~/adp255/env_adp255/lib/python3.9/site-packages/auto_ts/models/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;32mfrom[0m [0;34m.[0m[0mar_based[0m [0;32mimport[0m [0mBuildArima[0m[0;34m,[0m [0mBuildSarimax[0m[0;34m,[0m [0mBuildAutoSarimax[0m[0;34m,[0m [0mBuildVAR[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfrom[0m [0;34m.[0m[0mbuild_ml[0m [0;32mimport[0m [0mBuildML[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;32mfrom[0m [0;34m.[0m[0mbuild_prophet[0m [0;32mimport[0m [0mBuildProphet[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;32mfrom[0m [0;34m.[0m[0mbuild_pyflux[0m [0;32mimport[0m [0mbuild_pyflux_model[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/adp255/env_adp255/lib/python3.9/site-packages/auto_ts/models/build_prophet.py[0m in [0;36m<module>[0;34m[0m
[1;32m     17[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m [0;31m# type: ignore[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0;34m[0m[0m
[0;32m---> 19[0;31m [0;32mfrom[0m [0mfbprophet[0m [0;32mimport[0m [0mProphet[0m [0;31m# type: ignore[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m [0;32mfrom[0m [0mfbprophet[0m[0;34m.[0m[0mdiagnostics[0m [0;32mimport[0m [0mcross_validation[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m [0;32mfrom[0m [0mfbprophet[0m[0;34m.[0m[0mdiagnostics[0m [0;32mimport[0m [0mperformance_metrics[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/adp255/env_adp255/lib/python3.9/site-packages/fbprophet/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;31m# of patent rights can be found in the PATENTS file in the same directory.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mfrom[0m [0mfbprophet[0m[0;34m.[0m[0mforecaster[0m [0;32mimport[0m [0mProphet[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;34m[0m[0m
[1;32m     10[0m [0m__version__[0m [0;34m=[0m [0;34m'0.5'[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/adp255/env_adp255/lib/python3.9/site-packages/fbprophet/forecaster.py[0m in [0;36m<module>[0;34m[0m
[1;32m     18[0m [0;34m[0m[0m
[1;32m     19[0m [0;32mfrom[0m [0mfbprophet[0m[0;34m.[0m[0mdiagnostics[0m [0;32mimport[0m [0mprophet_copy[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 20[0;31m [0;32mfrom[0m [0mfbprophet[0m[0;34m.[0m[0mmake_holidays[0m [0;32mimport[0m [0mget_holiday_names[0m[0;34m,[0m [0mmake_holidays_df[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     21[0m [0;32mfrom[0m [0mfbprophet[0m[0;34m.[0m[0mmodels[0m [0;32mimport[0m [0mprophet_stan_model[0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m from fbprophet.plot import (plot, plot_components, plot_forecast_component,

[0;32m~/adp255/env_adp255/lib/python3.9/site-packages/fbprophet/make_holidays.py[0m in [0;36m<module>[0;34m[0m
[1;32m     14[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m [0;34m[0m[0m
[0;32m---> 16[0;31m [0;32mimport[0m [0mfbprophet[0m[0;34m.[0m[0mhdays[0m [0;32mas[0m [0mhdays_part2[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     17[0m [0;32mimport[0m [0mholidays[0m [0;32mas[0m [0mhdays_part1[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0;34m[0m[0m

[0;32m~/adp255/env_adp255/lib/python3.9/site-packages/fbprophet/hdays.py[0m in [0;36m<module>[0;34m[0m
[1;32m     14[0m [0;34m[0m[0m
[1;32m     15[0m [0;32mfrom[0m [0mconvertdate[0m[0;34m.[0m[0mislamic[0m [0;32mimport[0m [0mfrom_gregorian[0m[0;34m,[0m [0mto_gregorian[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 16[0;31m [0;32mfrom[0m [0mholidays[0m [0;32mimport[0m [0mWEEKEND[0m[0;34m,[0m [0mHolidayBase[0m[0;34m,[0m [0measter[0m[0;34m,[0m [0mrd[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     17[0m [0;32mfrom[0m [0mlunardate[0m [0;32mimport[0m [0mLunarDate[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0;34m[0m[0m

[0;31mImportError[0m: cannot import name 'easter' from 'holidays' (/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/holidays/__init__.py)
ImportError: cannot import name 'easter' from 'holidays' (/Users/ronaldogamermann/adp255/env_adp255/lib/python3.9/site-packages/holidays/__init__.py)

